datasets:
  feature_face_caption:
    build_info:
      ann_path: /datas/store163/othsueh/Corpus/IEMOCAP/Cross_validation/fold5_train.pickle
      image_path: /datas/store163/othsueh/Corpus/IEMOCAP/processed_videoframes
    data_type: images
