datasets:
  feature_face_caption:
    data_type: images
    
    build_info:
      # image_path: /home/user/selected_face/first_face/images
      image_path: /datas/store163/othsueh/Corpus/IEMOCAP/processed_videoframes

      ann_path: /datas/store163/othsueh/Corpus/IEMOCAP/data_collected_woother.pickle
      # ann_path: /home/user/selected_face/face_emotion/all_label_NCEV.txt
      # ann_path: /home/user/selected_face/face_emotion/target_label_list_0512_smp.txt
