model:
  arch: minigpt_v2
  model_type: pretrain
  max_txt_len: 500
  end_sym: "</s>"
  low_resource: False
  prompt_template: '[INST] {} [/INST]'
  llama_model: "/datas/store163/othsueh/Emotion-LLaMA/checkpoints/Llama-2-7b-chat-hf"
  ckpt: "/datas/store163/othsueh/Emotion-LLaMA/checkpoints/save_checkpoint/20241130122/checkpoint_29.pth"
  lora_r: 64
  lora_alpha: 16

datasets:    
  feature_face_caption:  #
    batch_size: 1
    vis_processor:
      train:
        name: "blip2_image_train"
        image_size: 224
    text_processor:
      train:
        name: "blip_caption"
    sample_ratio: 30

evaluation_datasets:
  feature_face_caption:
    eval_file_path: /datas/store163/othsueh/Corpus/IEMOCAP/data_collected_woother_5.pickle

    image_path: /datas/store163/othsueh/Corpus/IEMOCAP/processed_videoframes

    max_new_tokens: 500
    batch_size: 1

run:
  task: image_text_pretrain
  name: minigptv2_evaluation
  save_path: /datas/store163/othsueh/Emotion-LLaMA/results
